#! /bin/sh
#
# Script to check PFsense VPN tunnel status
# Chris Edwards | Nasstar | Jun 2017


OPTIND=1         # Reset in case getopts has been used previously in the shell.

while getopts "h?vuH:" opt; do
    case "$opt" in
    h|\?)
    	echo "Check PF ipsec: enumerate and check status of tunnels on pfsense unit"
	echo "-H <hostname> -u <username> -h this message"
	echo "user vpncheck should be created on pfsense and authorized keys imported"
	exit 0
	;;
    H) 
    	host=$OPTARG
    	;;
    esac
done

shift $((OPTIND-1))

[ "$1" = "--" ] && shift

User=vpncheck
Status=""
exit=0

# Get the list of tunnels

tunnels=$(ssh $User@$host sudo ipsec statusall | grep remote | cut -d "[" -f2 | cut -d "]" -f1 | grep -v bypass)
carp=$(ssh $User@$host ifconfig | egrep -c MASTER)


 if [ $carp = 0 ]; then
        printf "OK - No Tunnels Enabled\n"
        exit 0
 else
# Now for each entry check if it's online
for tunnel in $tunnels; do
    installed=$(ssh $User@$host sudo ipsec statusall | egrep $tunnel | egrep -c ESTABLISHED)
  if [ $installed = 1 ]; then
        # everythings cool
        printf "Peer: $tunnel Established. \n"
  else
        # everythings not cool
        printf "Peer: $tunnel Critical. \n"
        exit=2
  fi
done
fi
# Lets dump some statuses and getout of here

exit $exit
